#! /bin/bash
set -x
if [ -z $1 ] ; then

 echo "Error, no port has been sent to the script " && exit 1

fi

echo "New Port= $1"

script_path=$(pwd)

	cd ..

project=${PWD##*/}

	cd ..

new_script_path=$(pwd)

echo "Copiage de ${project} vers ${new_script_path}/${project}${1}"

# cp -r ${project} ${project}${1}
rsync -ra ${project} ${project}${1}

echo "Copie Terminé"

cd ${new_script_path}/${project}${1}/InterfaceDeLaMort/BasicExpressSite-master

echo "Déplacement vers le nouveau serveur"
echo "Changement du port d'écoute"
echo "je suis dans $(pwd)"
ls
sed -i '' 's/app.listen.*//' app.js

echo "app.listen(${1});" >> app.js

node app.js
