#! /bin/bash

if [ -z $1 ] ; then 

 echo "Error, no port has been sent to the script " && exit 1

fi

echo "New Port= $1"

script_path=$(pwd)

	cd ..

project=${PWD##*/}

	cd ..

new_script_path=$(pwd)

echo "Copiage de ${project} vers ${new_script_path}/${project}${1}"

cp -r ${project} ${project}${1}

cd ${new_script_path}/${project}${1}

sed -i  's/app.listen.*//' app.js

echo "app.listen(${1});" >> app.js

nohup npm start &
